name: TypeScript Lint and Reviewdog

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: windows-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: "18.x"  # Using LTS version for compatibility

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        npm install --save-dev eslint @eslint/js @typescript-eslint/parser @typescript-eslint/eslint-plugin typescript

    # Step 4: Run ESLint (For debugging)
    - name: Run ESLint
      run: npx eslint "**/*.{ts,tsx}"

    # Step 5: Run ESLint with Reviewdog
    - name: Run ESLint with Reviewdog
      uses: reviewdog/action-eslint@v1
      with:
        reporter: github-pr-review
        eslint_flags: "-c eslint.config.mjs **/*.{ts,tsx}"
        level: error
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}