name: TypeScript Lint and Reviewdog

on:
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22.11.0'

      - name: Install Dependencies
        run: npm ci  

      - name: Verify ESLint Installation
        run: npx eslint --version 

      - name: Run ESLint with Reviewdog
        run: npm run lint
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
